# Site
name: "Digital Avenue IT"
title: "Digital Avenue"
description: "Digital Avenue Carefully Verified DevOps and System Admin Tutorials For Kubernetes, Docker, Jenkins, Azure, AWS, Linux and more. Learn DevOps Now."
url: https://digitalavenue.dev
baseurl: ''
favicon: 'assets/images/favicon-DA.png'
logo: 'assets/images/logo-DA.gif'
permalink: /:year/:month/:day/:title
paginate: 12
timezone: 'Europe/Vienna'

# Set <USERNAME>/<PROJECT> to display the button to the project
repository: chriskyfung/amp-affiliately-jekyll-theme

# Navigation features
nav:
  buttons:
    gh_sponsors: false # Show GitHub Sponsors button
  global:
    home: true
    menu: true
    dropdown: true # Show menu with dropdown submenu
  local:
    items:
      - name: Features
        url: category/feature/
      - name: Docs
        url: category/doc/
      - name: Samples
        url: category/sample/
      - name: DevOps
        url: category/devops/
    menu: true
    title:
      limit: 40

# List Sorting
sort_categories: false
sort_tags: true

# Content Post-processing
target_blank: false
anchor_link: true

# Sidebar Features
sidebar:
  featured: true
  recent_posts: true

# # AddThis Inline Share Buttons
# addthis: 
#   pid: ra-5d01c83d522ad580 # Addthis profile id
#   wid: 7kfz # Addthis widget id

# Disqus Comments
# amp_disqus: 
#   shortname: 'chriskyfung' # Disqus shortname
#   url: 'https://chriskyfung.gitlab.io/disqus-amp/' #baseurl of your AMP disqus iframe element
#   height: 580

# Google Custom Search Engine ID
cse_id: 011006674894885990812:tjln7k0nyjx 

# Analytics
ga4: 'G-HP4LN87NJE' # Google Analytics 4 Measurement ID
gtm: 'GTM-WQMQK3X' # Google Tag Manager ID

# Google Ads
adstyle: true
adsense: 
  client_id: 'ca-pub-4819282024314540' # Google Adsense client ID
  auto_ads: true
  ad_slot:
    # before_content: 2454411055 # Ad Slot that places before content
    sidebar: 1391498756 # Ad Slot that places to sidebar

# Soical Buttons
social:
  facebook: chriskyfung
  pinterest: chriskyfung
  github : chriskyfung
  medium: chriskyfung

# Buy Me a Coffee
buymeacoffee: chriskyfung

# Copyright Start Year
copyright: 
  prefix: 
  ownership: Chris KY FUNG
  link: https://chriskyfung.github.io/

# Cookie Consent Notice
consent: true
consent_dev_mode: false
amp_optimizer: true
script_hash:
  consent_gsc: sha384-n2-YMnb2FkeDk-Ca2pVnoYSR2FqNKqKgTwfK_UI0EAeVRCAHgCDjsecHJpVMv3Sl

# Plugins
plugins: 
  - jekyll-archives
  - jekyll-feed
  - jekyll-minifier
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks: 
    category: '/category/:name/'
    tag: '/tag/:name/'

# Other
markdown: kramdown
highlighter: rouge

jekyll-minifier:
  exclude: 'feed.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns

relative_links:
  enabled: true
  collections: true

# Directories and/or files from the conversion
exclude:
  - frontmatter.json
  - gulpfile.js
  - LICENSE
  - package-lock.json
  - package.json
  - README.md

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: false
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/images/", "/assets/images", "/assets/img/"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to excludes
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################